const actionTypes = {
  SET_CART_HIDDEN: "SET_CART_HIDDEN",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_CARTITEM: "REMOVE_CARTITEM",
  DECREASE_REMOVE_CARTITEM: "DECREASE_REMOVE_CARTITEM",
};

export default actionTypes;
